name: codercrack
region: nyc
static_sites:
  - name: web
    github:
      repo: sasegura/codercrack
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: out
    routes:
      - path: /
    catchall_document: index.html
